version: '2.1'

volumes:

  makemkv-builder:
    driver: local

services:

  makemkv-builder:
    build: .
    image: makemkv-builder
    container_name: makemkv-builder
    volumes:
      - makemkv-builder:/output
#      - ./output:/output
